services:
  # MongoDB
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    restart: always
    ports:
      - "27017:27017" # Expose MongoDB sur le port par défaut

  # Node.js
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    restart: always
    depends_on:
      - db
    environment:
      PORT: 9999
      DATABASE: mongodb://db:27017/koodiarana # Port interne correct
      JWT_SECRET: $2b$10$Sjzdakezna2Qy3y/WciWM4GkEq.RktXLhztghzGJynA649M14njAS
      OTP_SECRET: koodiaranabyiantsosynykazazanyAZERTY
      SOCIETY_EMAIL: iantsochristianrazafindrazaka@gmail.com
      SOCIETY_PASSWORD: ggvt mblh hyve vvlz
