services:
  # MongoDB
  # db:
  #   image: mongo
  #   environment:
  #    MONGO_LOCAL: mongodb://localhost:27017/koodiarana
  #    MONGO_INITDB_ROOT_USERNAME: sass
  #    MONGO_INITDB_ROOT_PASSWORD: realpasssass
  #    MONGO_INITDB_DATABASE: admin
  #   restart: always
  #   ports:
  #     - "27017:27017" # Expose MongoDB sur le port par défaut

  # Node.js
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    restart: always
    # depends_on:
    #   - db
    environment:
      PORT: 9999
      DATABASE: mongodb://46.202.134.188:27017/koodiarana
      JWT_SECRET: $2b$10$Sjzdakezna2Qy3y/WciWM4GkEq.RktXLhztghzGJynA649M14njAS
      OTP_SECRET: koodiaranabyiantsosynykazazanyAZERTY
      SOCIETY_EMAIL: iantsochristianrazafindrazaka@gmail.com
      SOCIETY_PASSWORD: ggvt mblh hyve vvlz
