services:
  # mongo
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: koodiarana
      MONGO_INITDB_ROOT_PASSWORD: koodiarana
    restart: always
    ports:
      - "8081:8081"

  # Nodejs
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    restart: always
    depends_on:
      - db
    environment:
      PORT: 9999
      DATABASE: mongodb://db:8081/koodiarana
      JWT_SECRET: $2b$10$Sjzdakezna2Qy3y/WciWM4GkEq.RktXLhztghzGJynA649M14njAS
      OTP_SECRET: koodiaranabyiantsosynykazazanyAZERTY
      SOCIETY_EMAIL: iantsochristianrazafindrazaka@gmail.com
      SOCIETY_PASSWORD: ggvt mblh hyve vvlz
